import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('push', (event) => {
  const data = event.data ? event.data.json() : { title: 'Fasty', body: 'Nueva notificación' };
  
  const options = {
    body: data.body,
    icon: '/pwa-192x192.png',
    badge: '/favicon.ico',
    vibrate: [500, 200, 500, 200, 500, 200, 1000], // Patrón de vibración agresivo estilo llamada
    requireInteraction: true, // Obliga a tocarla para que desaparezca
    silent: false, // Asegura que no esté silenciada (suena el tono por defecto)
    tag: data.title.includes('Pedido') ? 'nuevo-pedido' : 'notificacion-general', // Evita spam
    data: {
      url: data.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      const url = event.notification.data.url;
      
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }
      
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
